### ISSUE TITLE
Offentlige styrelsers relation til ministerier

### ISSUE THREAD

**Issue by pebran** [digst/Basisanvendelsesprofil-for-organisation#5]
Oprindeligt stillet spørgsmål af mej-kombit:

- Er en styrelse en underorganisation af et ministerium? I et eksempel er den angivet med relationstypen "relateret til".

**Comment by pebran** [comment]
Det er ikke lykkedes at finde det nævnte eksempel.

**Comment by mej-kombit** [comment]
@pebran, kan du lukke dette issue?
